# Generated by Django 3.2.5 on 2021-12-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Place name')),
                ('category', models.CharField(max_length=350, verbose_name='Place category')),
                ('address', models.CharField(max_length=350, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('latitude', models.CharField(max_length=350, verbose_name='Place latitude')),
                ('longitude', models.CharField(max_length=350, verbose_name='Place longitude')),
                ('is_site_featured', models.BooleanField(default=True, verbose_name='Is site featured')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/places_imgs')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Place image',
                'verbose_name_plural': 'Place images',
            },
        ),
    ]
