# Generated by Django 3.2.5 on 2021-12-31 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='place.png', max_length=255, verbose_name='Place image'),
            preserve_default=False,
        ),
    ]
